import LogicSubmissions.Logic

namespace CxyBfsCertificate

open NesyLinkFormalization

/- Generated by utils/export_cxy_bfs_lean_certificate.py.
   Source: mathematical_logic/task_1, seed=0, raw pixels -> extract_scene -> bfs. -/
def pythonBfsState : SymbolicState := {
  player := (4, 6)
  exits := [(4, 0), (5, 0), (0, 3)]
  walls := [(0, 2), (1, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2), (0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5), (6, 5)]
  traps := []
  monsters := []
  chests := [(0, 3)]
  buttons := []
  switches := []
  npcs := []
  gaps := []
  bridges := []
  pressedButtons := []
  switchCount := 0
  completed := false
  inventory := { keys := 0, gold := 0, health := 5,
                 hasSword := true, hasShield := true }
}

def pythonBfsStart : Position := (4, 6)
def pythonBfsGoals : List Position := [(1, 3), (0, 4)]
def pythonBfsPath : List Position := [(4, 6), (5, 6), (6, 6), (7, 6), (7, 5), (7, 4), (7, 3), (6, 3), (5, 3), (4, 3), (3, 3), (2, 3), (1, 3)]

theorem python_bfs_checker_accepts :
    checkPathPlan pythonBfsState pythonBfsStart pythonBfsGoals pythonBfsPath = true := by
  native_decide

theorem python_bfs_path_sound :
    PathPlanSound pythonBfsState pythonBfsStart pythonBfsGoals pythonBfsPath := by
  exact checkPathPlan_sound python_bfs_checker_accepts

end CxyBfsCertificate
