from __future__ import annotations

import argparse
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from nesylink.env import make_env
from submissions.robust_final_agent import approach_tiles, bfs, extract_scene, manhattan


TASK_ID = "mathematical_logic/task_1"


def lean_position(pos: tuple[int, int]) -> str:
    return f"({pos[0]}, {pos[1]})"


def lean_positions(positions) -> str:
    ordered = sorted(set(positions), key=lambda pos: (pos[1], pos[0]))
    return "[" + ", ".join(lean_position(pos) for pos in ordered) + "]"


def build_certificate(seed: int) -> str:
    env = make_env(
        task_id=TASK_ID,
        api="gym",
        render_mode="rgb_array",
        auto_reset_on_step=True,
        observation_mode="pixels",
    )
    try:
        obs, _raw_info = env.reset(seed=seed)
    finally:
        env.close()

    scene = extract_scene(obs)
    if not scene.chests:
        raise RuntimeError("pixel extractor found no chest in Task 1 initial frame")

    target_chest = min(scene.chests, key=lambda pos: (manhattan(scene.player, pos), pos))
    goals = approach_tiles(scene, target_chest, set())
    if not goals:
        raise RuntimeError(f"no safe approach tile for chest {target_chest}")

    path = bfs(scene, goals, set())
    if not path:
        raise RuntimeError(f"cxy bfs found no path from {scene.player} to {sorted(goals)}")

    exits = set().union(*scene.exits.values())
    return f'''import LogicSubmissions.Logic

namespace CxyBfsCertificate

open NesyLinkFormalization

/- Generated by utils/export_cxy_bfs_lean_certificate.py.
   Source: {TASK_ID}, seed={seed}, raw pixels -> extract_scene -> bfs. -/
def pythonBfsState : SymbolicState := {{
  player := {lean_position(scene.player)}
  exits := {lean_positions(exits)}
  walls := {lean_positions(scene.walls)}
  traps := {lean_positions(scene.traps)}
  monsters := {lean_positions(scene.monsters)}
  chests := {lean_positions(scene.chests)}
  buttons := {lean_positions(scene.buttons)}
  switches := {lean_positions(scene.switches)}
  npcs := {lean_positions(scene.npcs)}
  gaps := {lean_positions(scene.gaps)}
  bridges := {lean_positions(scene.bridges)}
  pressedButtons := []
  switchCount := 0
  completed := false
  inventory := {{ keys := 0, gold := 0, health := 5,
                 hasSword := true, hasShield := true }}
}}

def pythonBfsStart : Position := {lean_position(scene.player)}
def pythonBfsGoals : List Position := {lean_positions(goals)}
def pythonBfsPath : List Position := {lean_positions_in_order(path)}

theorem python_bfs_checker_accepts :
    checkPathPlan pythonBfsState pythonBfsStart pythonBfsGoals pythonBfsPath = true := by
  native_decide

theorem python_bfs_path_sound :
    PathPlanSound pythonBfsState pythonBfsStart pythonBfsGoals pythonBfsPath := by
  exact checkPathPlan_sound python_bfs_checker_accepts

end CxyBfsCertificate
'''


def lean_positions_in_order(positions) -> str:
    return "[" + ", ".join(lean_position(pos) for pos in positions) + "]"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export one real cxy Python BFS path as a Lean certificate."
    )
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("LogicSubmissions/CxyBfsCertificate.lean"),
    )
    args = parser.parse_args()

    certificate = build_certificate(args.seed)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(certificate, encoding="utf-8")
    print(f"wrote {args.output} for {TASK_ID} seed={args.seed}")


if __name__ == "__main__":
    main()
